on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun ci

      - name: Build the library
        run: bun run build

      - name: Run unit tests
        run: bun run test & bun run check
